<table> <tr>
        <td  style="background-color:#ffffff;">
            <a href="http://qworld.lu.lv" target="_blank"><img src="../images/qworld.jpg" width="25%" align="left"> </a></td>
        <td style="background-color:#ffffff;vertical-align:bottom;text-align:right;">
            prepared by <a href="http://abu.lu.lv" target="_blank">Abuzer Yakaryilmaz</a> (<a href="http://qworld.lu.lv/index.php/qlatvia/" target="_blank">QLatvia</a>)
        </td>        
</tr></table>

<table width="100%"><tr><td style="color:#bbbbbb;background-color:#ffffff;font-size:11px;font-style:italic;text-align:right;">This cell contains some macros. If there is a problem with displaying mathematical formulas, please run this cell to load these macros. </td></tr></table>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\I}{ \mymatrix{rr}{1 & 0 \\ 0 & 1}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \mspace{-1mu} #1 \mspace{-1.5mu} \rfloor } $

<h2> Probabilistic Operators</h2>

[Watch Lecture](https://youtu.be/zYgym4NVq6o)

Remember Asja's biased coins, and her coin-flipping protocol.

$
GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array} \equiv \begin{array}{c|cc} & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & 0.6 & 0.3 \\  \mathbf{1} & 0.4 & 0.7  \end{array}
$

We trace Asja's outcomes after two coin flips.

<b> At the beginning: </b>

<i> Remember the protocol:
<ol> 
    <li> whenever she gets a head, she flips one euro; </li>
    <li> whenever she gets a tail, she flips one cent; and </li>
    <li> she starts with flipping one euro by assuming that she got head from nowhere </li>
</ol>
</i>

She starts in state 0: $ v_0 = \myvector{1 \\ 0} $.

State 0 represents Head and state 1 represents Tail.

<b>After first coin flip:</b>

$  \mypar{ 
        GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array}
        }
    \mypar{
        CurrentState=\myvector{1 \\ 0}
    } $
    
Each entry of the new vector is calculated by a row and current state:

$
\myvector{  0.6 \cdot 1 \\ + \\ 0.3 \cdot 0 \\ \hline 0.4 \cdot 1 \\ + \\ 0.7 \cdot 0  }
=
\myvector{ 0.6 + 0 \\ 0.4 + 0 }
=
\myvector{0.6 \\ 0.4}.
$

<b>After second coin flip:</b>

$  \mypar{ 
        GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array}
        }
    \mypar{
        CurrentState=\myvector{0.6 \\ 0.4}
    } $
    
Each entry of the new vector is calculated by a row and current state:

$
\myvector{  0.6 \cdot 0.6 \\ + \\ 0.3 \cdot 0.4 \\ \hline 0.4 \cdot 0.6 \\ + \\ 0.7 \cdot 0.4  }
=
\myvector{ 0.36 + 0.12 \\ 0.24 + 0.28 }
=
\myvector{0.48 \\ 0.52}.
$

<b>Coin-flipping protocol</b> of Asja is a <i>probabilistic operator</i>.

Similarly to any operator, depending on the current state, Asja's coin-flipping protocol determines the next state.

$$
    \myvector{1 \\ 0} \xrightarrow{\mbox{Asja's coin-flipping protocol}} \myvector{0.6 \\ 0.4}
    \xrightarrow{\mbox{Asja's coin-flipping protocol}}  \myvector{0.48 \\ 0.52}.
$$

<font color="blue"><b>A probabilistic operator evolves the system from a probabilistic state to a probabilistic state.</b></font>

Asja's coin-flipping protocol transforms $ \myvector{ 0.8 \\ 0.2 } $ to $ \myvector{ 0.54 \\ 0.46 } $.

When calculating the new state, we use the table $  GameCoins = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array} $ and the current state $ \myvector{ 0.8 \\ 0.2 } $:

$$
    \myvector{ \myarray{c}{0.6 \cdot 0.8 \\ + \\ 0.3 \cdot 0.2} \\ \hline \myarray{c}{0.4 \cdot 0.8 \\ + \\ 0.7 \cdot 0.2} } = \myvector{ \myarray{c}{0.48 + 0.06} \\ \myarray{c}{0.32 + 0.14}  } = \myvector{ 0.54 \\ 0.46 }.
$$

<h3> Probabilistic operator </h3>

A probabilistic operator can be represented as a square table or matrix.

The entries of a probabilistic operator represent the transition probabilities between the states.

Therefore, <b>each entry is nonnegative.</b>

Each column represents the transition probabilities from a state to all states. Therefore, <b>the summation of all entries in each column is 1</b>, i.e., probability 1 is distributed to all states. 

Any matrix satisfying these two properties is called a <b> stochastic matrix</b>.

A probabilistic operator is a stochastic matrix, and vice versa.

<i> Remark that the operator of any linear system is represented as a matrix. </i>

<h3> Probabilistic evolution </h3>

A probabilistic state is a stochastic vector,  say $ v $.

A probabilistic operator is a stochastic matrix, say $ A $,

If probabilistic operator $ A $ is applied to probabilistic state $ v $, the new state, say $v'$, is calculated as 

$$  v' = A \cdot v. $$

<i> Remark that the evolution of linear system is represented by matrix-vector multiplication. </i>

If we represent $ GameCoins $ as a matrix: $ \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } $, then the new probabilistic state is calculated as

$$
    \myvector{ 0.54 \\ 0.46 } = \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } \myvector{ 0.8 \\ 0.2 }.
$$

<h3> Task 1 </h3>

The operator $ GameCoins = \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } $ is applied to the probabilistic state $ \myvector{ 0.1 \\ 0.9 } $. 

Then, the new probabilistic state is

$$ \mymatrix{cc}{ 0.6 & 0.3 \\ 0.4 & 0.7 } \myvector{ 0.1 \\ 0.9 } = \myvector{ 0.33 \\ 0.67 } $$.

Please verify the correctness of matrix-vector multiplication.

In [1]:
print(0.6 * 0.1 + 0.3 * 0.9)
print(0.4 * 0.1 + 0.7 * 0.9)

0.33
0.67


<h3> Task 2 </h3>

We are given the following probabilistic operator: $ B =  \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $.

What is the transition probability from the second state to third state?

What is the transition probability from the third state to first state?

What is the transition probability from the first state to second state?

In [ ]:
# answers:
# 0.3
# 0
# 0.2

<h3>Task 3</h3>

Randomly construct a $ (3 \times 3 ) $-dimensional probabilistic operator.

That is, randomly determine the entries of the matrix that represents a probabilistic operator.

In [11]:
#
# your solution is here
#
# SOLUTION 1
from random import randrange

a = randrange(101)/100
b = randrange(int(101 - a))/100
c = 1 - (a + b)
d = randrange(101)/100
e = randrange(int(101 - d))/100
f = 1 - (d + e)
g = 1 - (a + d)
h = 1 - (b + e)
i = 1 - (c + f)
rand_prob_op = [
                [a, b, c],
                [d, e, f],
                [g, h, i]
                ]
print(a + d + g, b + e + h, c + f + i)
rand_prob_op

1.0 1.0 1.0


[[0.51, 0.97, -0.48],
 [0.4, 0.4, 0.19999999999999996],
 [0.08999999999999997, -0.3700000000000001, 1.28]]

In [17]:
# SOLUTION 2

rand_prob_op = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

normal = [0, 0, 0]
for i in range(3):
    for j in range(3):
        
        rand_prob_op[j][i] = randrange(101)

        normal[i] += rand_prob_op[j][i]
    
for i in range(3):
    for j in range(3):
        rand_prob_op[j][i] /= normal[i]

sum = [0,0,0]
for j in range(3):
    for i in range(3):
        sum[j] += rand_prob_op[i][j]

print(sum) 
rand_prob_op


[1.0, 1.0, 1.0]


[[0.38461538461538464, 0.3432203389830508, 0.20833333333333334],
 [0.17647058823529413, 0.326271186440678, 0.5],
 [0.43891402714932126, 0.3305084745762712, 0.2916666666666667]]

<a href="B15_Probabilistic_Operators_Solutions.ipynb#task3">click for our solution</a>

<h3> Task 4 </h3>

What is the new probabilistic state if the operator $ B =  \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $ is applied to the state $ \myvector{ 0.1 \\ 0.3 \\ 0.6 } $.

Please find the result by using matrix-vector multiplication.

Please do not use any python library for matrix-vector multiplication. 

<i> The new probabilistic state should be $ \myvector{0.22 \\ 0.47 \\ 0.31} $. </i>

In [3]:
# operator B
B = [
    [0.4,0.6,0],
    [0.2,0.1,0.7],
    [0.4,0.3,0.3]
]

# the current state
v = [0.1,0.3,0.6]

#
# your solution is here
#
import numpy as np
B = np.array(B)
v = np.array(v)
B.shape


(3, 3)

In [4]:
new_state = np.empty(B.shape[0])

for i in range(B.shape[1]):
    new_state[i] = 0
    for j in range(B.shape[0]):
        new_state[i] += B[i][j] * v[j]
        
new_state

array([0.22, 0.47, 0.31])

<a href="B15_Probabilistic_Operators_Solutions.ipynb#task4">click for our solution</a>

<h3> Task 5 </h3>

Write a function named <i>linear_evolve</i> that takes a probabilistic operator and a probabilistic state, and then returns the new probabilistic state.

Please do not use any python library for matrix-vector multiplication.

Your function should work for any dimension.

Save your function so that you can use it later.
<br><br>
<div style="background-color:#f8f8f8;">
<b><u>Write the content of a code cell</u></b> into an external file:
    
    %%writefile linear_evolve.py
This command should be placed in the first line of cell, and then the cell should be executed.
</div>

Test your function on $ B = \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $ and $ \myvector{0.1 \\ 0.3 \\ 0.6} $. 

The new probabilistic state should be $ \myvector{0.22 \\ 0.47 \\ 0.31} $.

Then, evolve your system for 5, 10, 20, and 40 steps.

This system should evolve to a fixed probabilistic state.

Change your initial state to  $ \myvector{1 \\ 0 \\ 0} $, and see whether the converged state is the same or not.

In [ ]:
# %%writefile linear_evolve.py

In [39]:
# run your script
# %run linear_evolve.py

# operator for the test
B = [
    [0.4,0.6,0],
    [0.2,0.1,0.7],
    [0.4,0.3,0.3]
]

# state for test
v = [0.1,0.3,0.6]

#
# your solution is here
#
def linear_evolve(prob_op, prob_state):
    import numpy as np
    prob_op = np.array(prob_op)
    prob_state = np.array(prob_state)
    
    new_state = np.empty(prob_op.shape[0])

    for i in range(prob_op.shape[1]):
        new_state[i] = 0
        for j in range(prob_op.shape[0]):
            new_state[i] += prob_op[i][j] * prob_state[j]

    return new_state

linear_evolve(B, v)

array([0.22, 0.47, 0.31])

In [41]:
for i in range(40):
    v = linear_evolve(B, v)
print(v)

v = [1, 0, 0]
for i in range(40):
    v = linear_evolve(B, v)
print(v)

[0.33333333 0.33333333 0.33333333]
[0.33333333 0.33333333 0.33333333]


<a href="B15_Probabilistic_Operators_Solutions.ipynb#task4">click for our solution</a>

<h3> Task 6 [extra] </h3>

The operator $ \widetilde{I} = \mymatrix{cc}{0.999 & 0.001\\ 0.001 & 0.999 } $ is very similar to Identity operator. However, it converges to a certain matrix.

Find $  \underbrace{\widetilde{I} \cdot \widetilde{I} \cdots \widetilde{I}}_{k\mbox{ times}} $ for $ k = 10, 100, 1000, 10000, 100000 $ and then guess the converging matrix.

In [43]:
v = [1, 0, 0]
B = [
    [0.999, 0.001],
    [0.001, 0.999]
]

for i in range(10):
    v = linear_evolve(B, v)
print(v)
for i in range(100):
    v = linear_evolve(B, v)
print(v)
for i in range(1000):
    v = linear_evolve(B, v)
print(v)
for i in range(100000):
    v = linear_evolve(B, v)
print(v)

[0.99008952 0.00991048]
[0.90117101 0.09882899]
[0.55418397 0.44581603]
[0.5 0.5]


<h3> Task 7 [extra] </h3>

Repeat Task 6 for the operator $ \widetilde{NOT} = \mymatrix{cc}{0.001 & 0.999\\ 0.999 & 0.001 } $.

In [44]:
v = [1, 0, 0]
B = [
    [0.001, 0.999],
    [0.999, 0.001]
]

for i in range(10):
    v = linear_evolve(B, v)
print(v)
for i in range(100):
    v = linear_evolve(B, v)
print(v)
for i in range(1000):
    v = linear_evolve(B, v)
print(v)
for i in range(100000):
    v = linear_evolve(B, v)
print(v)

[0.99008952 0.00991048]
[0.90117101 0.09882899]
[0.55418397 0.44581603]
[0.5 0.5]
